version: '3.6'
services:
  slate-build:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - "./build:/srv/slate/build"
      - "./source:/srv/slate/source"
    command: build
